#!/usr/bin/perl
$latex = 'uplatex -interaction=nonstopmode -kanji=utf-8 %O %S';
#$latex = 'xelatex %O %S';
$dvipdf = 'dvipdfmx %O -o %D %S';
$bibtex = 'pbibtex %O %B';
$pdf_mode = 3; # use dvipdf
$max_repeat = 5;
$pdf_update_method = 2;
$pdf_previewer = "zathura";
#$pdf_previewer = "mupdf";
# Prevent latexmk from removing PDF after typeset.
# $pvc_view_file_via_temporary = 0;
